#!/usr/bin/env python3

# Copyright 2017 Andrzej Cichocki

# This file is part of aridity.
#
# aridity is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# aridity is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with aridity.  If not, see <http://www.gnu.org/licenses/>.

import sys, os
from aridityimpl.grammar import Stream
from aridityimpl.context import Context
from aridityimpl.repl import Repl

def configpath(configname):
    for parent in os.environ['PATH'].split(os.pathsep):
        path = os.path.join(parent, configname)
        if os.path.exists(path):
            return path
    raise Exception("Not found: %s" % configname)

def main():
    context = Context()
    context.source(configpath(sys.argv[1]))
    for item in context.resolved(*sys.argv[2:]).unravel().items():
        print("%s=%s" % item) # FIXME: Proper encoding for bash eval.

if '__main__' == __name__:
    main()
